# Generated by Django 2.2.28 on 2022-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomized',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usercustomized',
            name='first_name',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usercustomized',
            name='last_name',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
