# Generated by Django 2.2.16 on 2022-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomized',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
