# Generated by Django 2.2.16 on 2022-12-11 13:30

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221209_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomized',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.validate_username]),
        ),
    ]
